services:
  app:
    container_name: app_service
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        APP_PORT: ${APP_PORT:-8000}
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/app
    depends_on:
      - db
      - cache
    command: >
      sh -c "
      uv run alembic upgrade head &&
      uv run uvicorn app.main:app --host 0.0.0.0 --port \$${APP_PORT:-8000}
      "

  db:
    container_name: app_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    container_name: app_cache
    image: redis:latest
    environment:
      REDIS_DB: ${CACHE_DB}
    ports:
      - "${CACHE_PORT}:${CACHE_PORT}"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  db_data:
